### ISSUE TITLE
Branch: iaa-Edition: Only world-specific scripts are recognized

### ISSUE THREAD

**Issue by kindlich** [Techlone/CraftTweaker#3]
Heyho,

Since someone deleted my post on the MT3-issue tracker and you now have issues enabled I'll just write it again xD

I downloaded and decompiled your latest iaa-branch and only the world-specific scripts are loaded, the other script folder (minecraft\scripts) remains untouched...

Even though you told me you wanted to write another version of MT in LUA, could you still try to fix that issue, as a lua MT won't support all of the mods in the near future xD

I'd do it myself but I just don't know that much about Java...

**Comment by Techlone** [comment]
Hmm it works for me. I'll see it when I'll have more time. Maybe something was broken in git version.

**Comment by kindlich** [comment]
Ok, here a Screenshot from the log:
http://puu.sh/pKhuT/fae0665c11.png

As you see, only the testworld.zs script is found/loaded...

What could be the cause is that I used an older Forge version as gradle couldnt download the 1492 version (something with a 403 - Forbidden serverside error...) So I used version 1225

**Comment by kindlich** [comment]
Tested some more with both, the 1.7.10 and the 1.8 versions, both don't seem to support the minecraft/scripts directory...

I tried to resolve it myself, but I'm just not good at reading/understanding Java code...

Do you know when you will have the time for taking a quick look into the code?

**Comment by Techlone** [comment]
Yes I didn't push all changes into iia-edition. I didn't think that I will push iia-edition at all :) I hope somewhere I fixed this issue...
